<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3><?php echo Mage::helper('cleaner')->__('Cache Management'); ?></h3>
            </td>
            <td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getMageTablesUrl(); ?>')" type="button" class="scalable">
                <span><span>
                <span><?php echo Mage::helper('cleaner')->__('Flush Magento Tables'); ?></span>
                </span></span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('cleaner')->__('Truncate magento cache tables.'); ?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getMageDirUrl(); ?>')" type="button" class="scalable">
                <span><span>
                <span><?php echo Mage::helper('cleaner')->__('Flush Magento Directories'); ?></span>
                </span></span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('cleaner')->__('Empty magento cache directories.'); ?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getRedisUrl(); ?>')" type="button" class="scalable">
                <span><span>
                <span><?php echo Mage::helper('cleaner')->__('Flush Redis'); ?></span>
                </span></span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('cleaner')->__('Empty data from current database.'); ?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getMemcachedUrl(); ?>')" type="button" class="scalable">
                <span><span>
                <span><?php echo Mage::helper('cleaner')->__('Flush Memcached'); ?></span>
                </span></span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('cleaner')->__('Empty cache and sessions.'); ?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <form action="<?php echo $this->getCdnUrl(); ?>" method="get">
                <button type="submit" class="scalable cleaner-valign">
                    <span><span>
                    <span><?php echo Mage::helper('cleaner')->__('Flush CDN'); ?></span>
                    </span></span>
                </button>
                <div class="field-100 cleaner-valign">
                    <input type="text" name="media_path" placeholder="Media Path" class="input-text no-changes">
                </div>
            </form>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('cleaner')->__('Empty cached files.'); ?>
        </td>
    </tr>
</table>
